from dataclasses import dataclass

@dataclass
class AIResult:
    category: str
    priority: str
    recommendation: str
    summary: str

CATEGORY_KEYWORDS = {
    "network": ["wifi", "internet", "dns", "vpn", "router", "network"],
    "hardware": ["laptop", "printer", "mouse", "keyboard", "screen", "hardware"],
    "software": ["error", "bug", "crash", "login", "password", "update", "software"],
    "security": ["breach", "phishing", "malware", "2fa", "mfa", "security"],
    "general": []
}

def analyze(title: str, description: str) -> AIResult:
    text = f"{title} {description}".lower()

    best_cat = "general"
    best_score = 0

    for cat, kws in CATEGORY_KEYWORDS.items():
        score = sum(1 for kw in kws if kw in text)
        if score > best_score:
            best_cat, best_score = cat, score

    urgent_words = ["urgent", "asap", "immediately", "down", "blocked", "critical"]
    if any(w in text for w in urgent_words):
        priority = "high"
    elif best_score > 0:
        priority = "medium"
    else:
        priority = "low"

    recommendation = {
        "network": "Check VPN/DNS settings; validate connectivity; review recent network changes.",
        "hardware": "Run diagnostics; check drivers/cables; replace component if recurring.",
        "software": "Collect logs; reproduce; validate recent updates; rollback if needed.",
        "security": "Isolate affected account/device; rotate credentials; run security scan; notify security team.",
        "general": "Request more details; assign to triage queue; classify manually."
    }[best_cat]

    summary = f"Classified as '{best_cat}', priority '{priority}'. Recommendation generated by AI module."

    return AIResult(best_cat, priority, recommendation, summary)
