from dataclasses import dataclass
from typing import Dict, List, Tuple

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB


@dataclass
class AIResult:
    category: str
    priority: str
    recommendation: str
    summary: str
    model: str
    confidence: float


TRAINING_DATA: List[Tuple[str, str]] = [
    ("VPN not connecting and internet down", "network"),
    ("WiFi keeps disconnecting, DNS not resolving", "network"),
    ("Router is down, network outage urgent", "network"),

    ("Printer not working, paper jam, office printer broken", "hardware"),
    ("Laptop screen flickering and keyboard not responding", "hardware"),
    ("Mouse not detected, hardware issue", "hardware"),

    ("App crashes on login after update, error shown", "software"),
    ("Bug in system, cannot login, password reset not working", "software"),
    ("System update broke the application, crash", "software"),

    ("Phishing email received, suspicious link, possible breach", "security"),
    ("Malware detected, urgent security incident", "security"),
    ("Account compromised, enable MFA/2FA", "security"),

    ("Need help, general request, please assist", "general"),
    ("Question about process, not sure what department", "general"),
]

RECOMMENDATIONS: Dict[str, str] = {
    "network": "Check VPN/DNS settings; validate connectivity; review recent network changes.",
    "hardware": "Run diagnostics; check drivers/cables; replace component if recurring.",
    "software": "Collect logs; reproduce; validate recent updates; rollback if needed.",
    "security": "Isolate affected account/device; rotate credentials; run security scan; notify security team.",
    "general": "Request more details; assign to triage queue; classify manually.",
}

URGENT_WORDS = ["urgent", "asap", "immediately", "down", "blocked", "critical", "breach", "malware"]


def compute_priority(title: str, description: str, confidence: float, category: str) -> str:
    text = f"{title} {description}".lower()

    if any(w in text for w in URGENT_WORDS):
        return "high"

    if confidence >= 0.55 and category != "general":
        return "medium"

    return "low"


class DualMLEngine:

    def __init__(self):
        self.vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=1)

        self.lr = LogisticRegression(max_iter=400)
        self.nb = MultinomialNB()

        self.is_ready = False

    def train(self):
        texts = [t for (t, y) in TRAINING_DATA]
        labels = [y for (t, y) in TRAINING_DATA]

        X = self.vectorizer.fit_transform(texts)

        self.lr.fit(X, labels)
        self.nb.fit(X, labels)

        self.is_ready = True

    def predict_lr(self, title: str, description: str) -> Tuple[str, float]:
        text = f"{title} {description}".lower()
        X = self.vectorizer.transform([text])
        proba = self.lr.predict_proba(X)[0]
        idx = int(proba.argmax())
        label = self.lr.classes_[idx]
        confidence = float(proba[idx])
        return label, confidence

    def predict_nb(self, title: str, description: str) -> Tuple[str, float]:
        text = f"{title} {description}".lower()
        X = self.vectorizer.transform([text])
        proba = self.nb.predict_proba(X)[0]
        idx = int(proba.argmax())
        label = self.nb.classes_[idx]
        confidence = float(proba[idx])
        return label, confidence


ENGINE = DualMLEngine()


def analyze_with(model_name: str, title: str, description: str) -> AIResult:
    if not ENGINE.is_ready:
        ENGINE.train()

    if model_name == "lr":
        category, confidence = ENGINE.predict_lr(title, description)
        model_label = "tfidf+logreg"
    elif model_name == "nb":
        category, confidence = ENGINE.predict_nb(title, description)
        model_label = "tfidf+naivebayes"
    else:
        raise ValueError("model_name must be 'lr' or 'nb'")

    priority = compute_priority(title, description, confidence, category)
    recommendation = RECOMMENDATIONS.get(category, RECOMMENDATIONS["general"])
    summary = (
        f"ML classified as '{category}' (confidence {confidence:.2f}), priority '{priority}'. "
        f"Recommendation generated by AI module."
    )

    return AIResult(
        category=category,
        priority=priority,
        recommendation=recommendation,
        summary=summary,
        model=model_label,
        confidence=confidence,
    )


def compare_models(title: str, description: str) -> Dict:

    lr_res = analyze_with("lr", title, description)
    nb_res = analyze_with("nb", title, description)

    winner = "lr" if lr_res.confidence >= nb_res.confidence else "nb"

    return {
        "lr": {
            "category": lr_res.category,
            "priority": lr_res.priority,
            "recommendation": lr_res.recommendation,
            "summary": lr_res.summary,
            "model": lr_res.model,
            "confidence": lr_res.confidence,
        },
        "nb": {
            "category": nb_res.category,
            "priority": nb_res.priority,
            "recommendation": nb_res.recommendation,
            "summary": nb_res.summary,
            "model": nb_res.model,
            "confidence": nb_res.confidence,
        },
        "winner": winner,
    }


def analyze(title: str, description: str) -> AIResult:

    return analyze_with("lr", title, description)